// Korean for every string the plugin shows; English is the key. Section and field names, and the values' meanings, stay as the format names them.
// `tests/ko.test.ts` fails on a `t("…")` or `msg("…")` in the source with no entry here, and on an entry nothing uses.
export const KO: Record<string, string> = {
  "(not in the list)": "(목록에 없음)",
  "1 = the game uses units.dat / weapons.dat for this type.": "1이면 게임이 이 종류에 units.dat / weapons.dat 값을 씁니다.",
  "A section name is one to four characters.": "섹션 이름은 한 글자에서 네 글자입니다.",
  "A set bit excludes that elevation; 0 is everywhere.": "켜진 비트는 그 높이를 제외합니다. 0이면 모든 곳입니다.",
  "A sprites.dat id for a pure sprite; a units.dat id when the pure-sprite flag is off (doors, traps).": "순수 스프라이트면 sprites.dat ID, 순수 스프라이트 플래그가 꺼져 있으면 units.dat ID입니다 (문, 함정).",
  "Add": "추가",
  "Added {name} ({n} bytes).": "{name}을(를) 추가했습니다 ({n}바이트).",
  "Add…": "추가…",
  "Alignment byte.": "정렬용 바이트.",
  "An offset is a number: 1234 or 0x4d2.": "오프셋은 숫자입니다: 1234 또는 0x4d2.",
  "Append": "끝에 추가",
  "Append a blank record at the end": "빈 레코드를 끝에 추가합니다",
  "Applied {n, plural, one {# section} other {# sections}}.": "섹션 {n}개를 적용했습니다.",
  "Apply": "적용",
  "Apply ({n})": "적용 ({n})",
  "Apply failed: {error}": "적용하지 못했습니다: {error}",
  "Byte offset of each string from the start of the section; index 0 has no entry.": "섹션 시작부터 각 문자열까지의 바이트 오프셋입니다. 인덱스 0은 항목이 없습니다.",
  "Bytes": "바이트",
  "Bytes past the end of the layout. The game ignores what it does not read.": "레이아웃 끝을 넘어선 바이트입니다. 게임은 읽지 않는 부분을 무시합니다.",
  "Cancel": "취소",
  "Centre of the footprint.": "차지하는 영역의 중심.",
  "Centre, in map pixels.": "중심, 맵 픽셀 단위.",
  "Change the four-character name": "네 글자 이름을 바꿉니다",
  "Changed here and not yet applied": "여기서 바꿨고 아직 적용하지 않음",
  "Choose a section on the left.": "왼쪽에서 섹션을 고르세요.",
  "Close": "닫기",
  "Could not read {file}: {error}": "{file}을(를) 읽지 못했습니다: {error}",
  "Declares {n} bytes but the file ended early": "{n}바이트라고 선언했지만 파일이 먼저 끝났습니다",
  "Delete record": "레코드 삭제",
  "Download the scenario file as Save would write it (scenario.chk, no archive)": "저장할 때 쓰는 그대로 시나리오 파일을 내려받습니다 (scenario.chk, 아카이브 없음)",
  "Download this section's bytes": "이 섹션의 바이트를 내려받습니다",
  "Drop every change and read the sections again": "모든 변경을 버리고 섹션을 다시 읽습니다",
  "EUD mask; 0 in ordinary maps.": "EUD 마스크. 일반 맵에서는 0입니다.",
  "Export": "내보내기",
  "Export .chk": ".chk 내보내기",
  "Exported {n} bytes.": "{n}바이트를 내보냈습니다.",
  "Failed: {error}": "실패했습니다: {error}",
  "Find": "찾기",
  "Find next (Enter); Shift+Enter finds the previous": "다음 찾기 (Enter). Shift+Enter는 이전을 찾습니다",
  "Fit to {n}": "{n}에 맞추기",
  "Fog of war: one byte per cell, one bit per player 1–8, set where that player starts unexplored. A map without MASK is fully fogged.": "전장의 안개: 칸마다 한 바이트, 플레이어 1–8마다 한 비트로, 그 플레이어가 탐색하지 않은 상태로 시작하는 곳에 켜집니다. MASK가 없는 맵은 전부 안개에 덮입니다.",
  "Forces: which force each of the eight playable slots belongs to, the four force names, and per-force flags.": "세력: 플레이 가능한 여덟 슬롯이 각각 속한 세력, 네 세력의 이름, 세력별 플래그.",
  "Found at {offset}.": "{offset}에서 찾았습니다.",
  "Game frames.": "게임 프레임.",
  "Hit points × 256.": "체력 × 256.",
  "How relatedSerial is linked.": "relatedSerial이 연결된 방식.",
  "Import .chk…": ".chk 가져오기…",
  "Import…": "가져오기…",
  "Index into the tileset's dddata.bin.": "타일셋 dddata.bin의 인덱스.",
  "Insert a blank {n}-byte record before the one under the cursor": "커서 아래 레코드 앞에 {n}바이트짜리 빈 레코드를 넣습니다",
  "Insert a new section": "새 섹션을 넣습니다",
  "Insert mode": "삽입 모드",
  "Insert mode: typed and pasted bytes are inserted rather than overwritten; Delete removes bytes. Also the Insert key.": "삽입 모드: 입력하거나 붙여 넣은 바이트를 덮어쓰지 않고 끼워 넣습니다. Delete는 바이트를 지웁니다. Insert 키로도 바뀝니다.",
  "Insert record": "레코드 삽입",
  "Inserted a blank record at {offset}.": "{offset}에 빈 레코드를 넣었습니다.",
  "Inspector": "검사기",
  "Interceptors or Scarabs.": "인터셉터 또는 스캐럽.",
  "Kept as bytes and written back unchanged": "바이트 그대로 두었다가 바꾸지 않고 다시 씀",
  "Kept the section.": "섹션을 그대로 두었습니다.",
  "Locations, 20 bytes each: 64 slots in an original map, 255 in Brood War. Slot 63 is Anywhere.": "로케이션, 각 20바이트: 오리지널 맵은 64슬롯, 브루드 워는 255슬롯. 슬롯 63은 Anywhere입니다.",
  "Map width and height in tiles.": "타일 단위의 맵 너비와 높이.",
  "Minerals or gas held by a resource unit.": "자원 유닛이 가진 미네랄 또는 가스.",
  "Mission briefings: the same record as TRIG with briefing action types.": "미션 브리핑: TRIG와 같은 레코드에 브리핑 액션 종류를 씁니다.",
  "Move down": "아래로 이동",
  "Move up": "위로 이동",
  "Moved.": "옮겼습니다.",
  "No bytes.": "바이트가 없습니다.",
  "No layout for this section. Hover the bytes for their offsets; the hex view still edits them.": "이 섹션의 레이아웃이 없습니다. 바이트 위에 포인터를 두면 오프셋이 보이고, 16진 보기에서 편집할 수 있습니다.",
  "Not found.": "찾지 못했습니다.",
  "Not part of the layout.": "레이아웃에 속하지 않습니다.",
  "Nothing to apply.": "적용할 것이 없습니다.",
  "Nothing to look for — type hex digits, text or a number.": "찾을 것이 없습니다. 16진 숫자, 텍스트 또는 숫자를 입력하세요.",
  "Nothing to paste — hex digits in the byte column, text in the text column.": "붙여 넣을 것이 없습니다. 바이트 열에는 16진 숫자, 텍스트 열에는 텍스트를 넣으세요.",
  "Occurrence {n} of {count}; the game combines them ({mode})": "{count}개 중 {n}번째. 게임이 이들을 합칩니다 ({mode})",
  "One byte per player group; non-zero means the trigger runs for that group.": "플레이어 그룹마다 한 바이트. 0이 아니면 트리거가 그 그룹에서 실행됩니다.",
  "Pad with zeros or cut to {n} bytes": "0으로 채우거나 잘라서 {n}바이트로 만듭니다",
  "Pasted {n, plural, one {# byte} other {# bytes}}.": "{n}바이트를 붙여 넣었습니다.",
  "Placed doodads, 8 bytes each. The game never reads this; it sees the tiles in MTXM and the overlay sprites in THG2.": "배치한 장식물, 각 8바이트. 게임은 이 섹션을 읽지 않고 MTXM의 타일과 THG2의 오버레이 스프라이트를 봅니다.",
  "Placed units, 36 bytes each, in the order they were placed.": "배치한 유닛, 각 36바이트, 배치한 순서대로.",
  "Read {n} bytes from {file} — Apply to keep them.": "{file}에서 {n}바이트를 읽었습니다. 유지하려면 적용하세요.",
  "Redo": "다시 실행",
  "Redo (Ctrl+Y)": "다시 실행 (Ctrl+Y)",
  "Remastered player colours: an RGB triple per playable slot, then a mode byte per slot saying whether the game uses it, the lobby choice, a random colour or COLR.": "리마스터 플레이어 색: 플레이 가능한 슬롯마다 RGB 세 값, 그다음 슬롯마다 게임이 그 색, 로비 선택, 무작위 색, COLR 중 무엇을 쓰는지 정하는 모드 바이트.",
  "Remove": "제거",
  "Remove the record under the cursor": "커서 아래 레코드를 지웁니다",
  "Remove this occurrence from the file": "파일에서 이 섹션을 제거합니다",
  "Remove {name}": "{name} 제거",
  "Remove {name} ({n} bytes) from the file?": "파일에서 {name}({n}바이트)을(를) 제거할까요?",
  "Removed the record at {offset}.": "{offset}의 레코드를 지웠습니다.",
  "Removed the section.": "섹션을 제거했습니다.",
  "Rename": "이름 바꾸기",
  "Renamed to {name}.": "이름을 {name}(으)로 바꿨습니다.",
  "Rename…": "이름 바꾸기…",
  "Replace the whole scenario with a .chk file": "시나리오 전체를 .chk 파일로 바꿉니다",
  "Replace this section's bytes with a file's (then Apply)": "이 섹션의 바이트를 파일의 바이트로 바꿉니다 (그다음 적용)",
  "Replaced the scenario with {file}.": "시나리오를 {file}(으)로 바꿨습니다.",
  "Resized to {n} bytes.": "{n}바이트로 크기를 바꿨습니다.",
  "Resource, score type or switch number, per type.": "종류에 따라 자원, 점수 종류 또는 스위치 번호.",
  "Revert": "되돌리기",
  "Reverted — every section read again from the map.": "되돌렸습니다. 모든 섹션을 맵에서 다시 읽었습니다.",
  "Scroll the map to {target} and select it": "맵을 {target}(으)로 스크롤하고 선택합니다",
  "Second player, destination location, amount, switch, AI script or properties slot, per type.": "종류에 따라 두 번째 플레이어, 목적지 로케이션, 양, 스위치, AI 스크립트 또는 속성 슬롯.",
  "Section Explorer": "섹션 탐색기",
  "Section Explorer: open a map first.": "섹션 탐색기: 먼저 맵을 여세요.",
  "Section Explorer: {text}": "섹션 탐색기: {text}",
  "Section Explorer…": "섹션 탐색기…",
  "Sections": "섹션",
  "Set the section's length (zero-padded or cut); Enter applies": "섹션 길이를 정합니다 (0으로 채우거나 자름). Enter로 적용",
  "Show on map": "맵에서 보기",
  "Sprites, 10 bytes each: pure sprites (a sprites.dat id with the pure flag) and unit sprites (doors and traps by units.dat id), plus doodad overlays.": "스프라이트, 각 10바이트: 순수 스프라이트(순수 플래그와 sprites.dat ID), 유닛 스프라이트(units.dat ID로 된 문과 함정), 그리고 장식물 오버레이.",
  "StarEdit's copy of the player controllers. The game reads OWNR.": "StarEdit이 따로 둔 플레이어 조종자 사본. 게임은 OWNR을 읽습니다.",
  "StarEdit's copy of the terrain without doodads: what is under each doodad. Same layout as MTXM. The game ignores it.": "장식물을 뺀 지형의 StarEdit 사본: 각 장식물 아래에 있는 것. MTXM과 같은 레이아웃이며 게임은 무시합니다.",
  "String index of a custom name, 0 for the default.": "사용자 지정 이름의 문자열 인덱스, 기본값이면 0.",
  "Switch names: 256 string indices, 0 for an unnamed switch.": "스위치 이름: 문자열 인덱스 256개, 이름 없는 스위치는 0.",
  "Technology restrictions, Brood War layout (44 technologies).": "기술 제한, 브루드 워 레이아웃 (기술 44개).",
  "Technology restrictions, original layout (24 technologies): per-player availability and researched state, global defaults, and whether each player uses them.": "기술 제한, 오리지널 레이아웃 (기술 24개): 플레이어별 사용 가능 여부와 연구 상태, 전체 기본값, 각 플레이어가 기본값을 따르는지.",
  "Technology settings, Brood War layout (44 technologies).": "기술 설정, 브루드 워 레이아웃 (기술 44개).",
  "Technology settings, original layout (24 technologies): use-default, then mineral, gas, time and energy costs.": "기술 설정, 오리지널 레이아웃 (기술 24개): 기본값 사용, 그다음 미네랄, 가스, 시간, 에너지 비용.",
  "The 64 Create Unit with Properties slots (CUWP), 20 bytes each; the action refers to them by slot number.": "속성 있는 유닛 생성 슬롯(CUWP) 64개, 각 20바이트. 액션은 슬롯 번호로 가리킵니다.",
  "The Remastered string table: like STR with 32-bit count and offsets, so a map may carry more than 65,535 bytes of text.": "리마스터 문자열 표: STR과 같지만 개수와 오프셋이 32비트라 맵이 65,535바이트가 넘는 텍스트를 담을 수 있습니다.",
  "The StarEdit version that wrote the file (11 for every release version).": "파일을 쓴 StarEdit 버전 (정식 버전은 모두 11).",
  "The StarEdit version that wrote the file (obsolete; 9 or 10). Not required.": "파일을 쓴 StarEdit 버전 (더 쓰이지 않음, 9 또는 10). 필수가 아닙니다.",
  "The colour of each of the eight playable slots, as an index into the game's colour table.": "플레이 가능한 여덟 슬롯의 색, 게임 색 표의 인덱스.",
  "The editor decodes this section; an applied edit is read back into the map.": "에디터가 이 섹션을 해석합니다. 적용한 편집은 맵으로 다시 읽힙니다.",
  "The editor has no layout for this section; the bytes are shown as they are.": "에디터에 이 섹션의 레이아웃이 없어 바이트를 그대로 보여 줍니다.",
  "The editor has unsaved changes here; what you see is what Save would write.": "에디터에 저장하지 않은 변경이 있습니다. 보이는 것은 저장하면 쓰일 내용입니다.",
  "The editor has unsaved changes that will be encoded here on Save": "에디터에 저장할 때 여기에 기록될, 저장하지 않은 변경이 있습니다",
  "The editor keeps this section as bytes and writes it back unchanged.": "에디터는 이 섹션을 바이트 그대로 두었다가 바꾸지 않고 다시 씁니다.",
  "The editor knows nothing about this section": "에디터가 이 섹션에 대해 아는 것이 없습니다",
  "The editor models this section: removing it changes what the map is.": "에디터가 이 섹션을 해석해 씁니다. 제거하면 맵의 내용이 바뀝니다.",
  "The file format revision. Decides which settings sections the game reads.": "파일 형식 개정 번호. 게임이 어느 설정 섹션을 읽을지 정합니다.",
  "The game reads {n} bytes here": "게임은 여기서 {n}바이트를 읽습니다",
  "The game's bookkeeping; StarEdit writes 0.": "게임의 내부 기록. StarEdit은 0을 씁니다.",
  "The isometric terrain lattice StarEdit's isometric brush works on: one cell per diamond, four edge values each. The game ignores it.": "StarEdit의 아이소메트릭 브러시가 다루는 아이소메트릭 지형 격자: 마름모마다 한 칸, 칸마다 가장자리 값 네 개. 게임은 무시합니다.",
  "The map type: RAWS for an original or hybrid map, RAWB for Brood War.": "맵 종류: 오리지널이나 하이브리드 맵은 RAWS, 브루드 워는 RAWB.",
  "The parser said: {warnings}": "파서 메시지: {warnings}",
  "The race of each of the twelve player slots.": "열두 플레이어 슬롯의 종족.",
  "The section's structure; click to jump": "섹션의 구조. 클릭하면 이동합니다",
  "The size is a whole number of bytes.": "크기는 바이트 단위의 정수입니다.",
  "The sound table: 512 string indices of the sound files in the archive (staredit\\wav\\…). Play WAV actions store the string index itself.": "사운드 표: 아카이브 안 사운드 파일(staredit\\wav\\…)의 문자열 인덱스 512개. Play WAV 액션은 문자열 인덱스 자체를 저장합니다.",
  "The string indices of the scenario's name and description.": "시나리오 이름과 설명의 문자열 인덱스.",
  "The string table: a 16-bit count, one 16-bit offset per string (1-based indices), then NUL-terminated latin-1 strings. Index 0 means no string.": "문자열 표: 16비트 개수, 문자열마다 16비트 오프셋 하나(인덱스는 1부터), 그다음 NUL로 끝나는 latin-1 문자열. 인덱스 0은 문자열 없음입니다.",
  "The terrain the game draws: one 16-bit tile id per cell, row by row, doodads stamped in. An id is a CV5 group (high 12 bits) and a tile within it (low 4).": "게임이 그리는 지형: 칸마다 16비트 타일 ID, 행 순서대로, 장식물이 찍힌 상태. ID는 CV5 그룹(상위 12비트)과 그 안의 타일(하위 4비트)입니다.",
  "The text, in offset order. A blob shared by several indices is listed once.": "오프셋 순서의 텍스트. 여러 인덱스가 함께 쓰는 덩어리는 한 번만 나옵니다.",
  "The tileset, as a 16-bit value the game masks to its low three bits.": "타일셋. 16비트 값이며 게임은 하위 3비트만 봅니다.",
  "The unit this one is linked to (a Nydus exit, an add-on's building).": "이 유닛이 연결된 유닛 (나이더스 출구, 애드온의 건물).",
  "The verification table: 256 seed values and 16 operation codes the game hashes the map's sections with. StarEdit writes the same table into every map; a map with a different one is refused.": "검증 표: 게임이 맵 섹션을 해시할 때 쓰는 시드 값 256개와 연산 코드 16개. StarEdit은 모든 맵에 같은 표를 쓰고, 다른 표가 든 맵은 거부됩니다.",
  "This rewrites the map and clears the undo history — there is no taking it back.": "맵을 다시 쓰고 실행 취소 기록을 지웁니다. 되돌릴 수 없습니다.",
  "This section is empty. Insert a record or bytes from the inspector, or paste hex here.": "이 섹션은 비어 있습니다. 검사기에서 레코드나 바이트를 넣거나 여기에 16진수를 붙여 넣으세요.",
  "Triggers, 2400 bytes each: 16 conditions, 64 actions, flags, one byte per player group and the game's current-action byte.": "트리거, 각 2400바이트: 조건 16개, 액션 64개, 플래그, 플레이어 그룹마다 한 바이트, 게임의 현재 액션 바이트.",
  "Type hex digits in the byte column or characters in the text column to change it.": "바꾸려면 바이트 열에 16진 숫자를, 텍스트 열에 글자를 입력하세요.",
  "Undo": "실행 취소",
  "Undo (Ctrl+Z in the hex view)": "실행 취소 (16진 보기에서 Ctrl+Z)",
  "Unique per unit within the map; Nydus and add-on links refer to it.": "맵 안에서 유닛마다 고유한 값. 나이더스와 애드온 연결이 이것을 가리킵니다.",
  "Unit availability: for each player and unit type whether it can be built, a global default per type, and whether each player follows the default.": "유닛 사용 가능 여부: 플레이어와 유닛 종류마다 생산할 수 있는지, 종류별 전체 기본값, 각 플레이어가 기본값을 따르는지.",
  "Unit count (0 = all), set/add/subtract, switch action, state or order, per type.": "종류에 따라 유닛 수(0 = 전부), 설정/더하기/빼기, 스위치 동작, 상태 또는 명령.",
  "Unit id, resource, score type or alliance status, per type.": "종류에 따라 유닛 ID, 자원, 점수 종류 또는 동맹 상태.",
  "Unit settings, Brood War layout: as UNIS with 130 weapons.": "유닛 설정, 브루드 워 레이아웃: UNIS와 같고 무기가 130개.",
  "Unit settings, original layout: per unit type a use-default byte, hit points (×256), shields, armour, build time, costs, name string; then 100 weapon damage and bonus values.": "유닛 설정, 오리지널 레이아웃: 유닛 종류마다 기본값 사용 바이트, 체력(×256), 실드, 방어력, 생산 시간, 비용, 이름 문자열. 그다음 무기 100개의 공격력과 추가 공격력.",
  "Untitled": "제목 없음",
  "Upgrade restrictions, Brood War layout (61 upgrades).": "업그레이드 제한, 브루드 워 레이아웃 (업그레이드 61개).",
  "Upgrade restrictions, original layout (46 upgrades): per-player maximum and start levels, global defaults, and whether each player uses them.": "업그레이드 제한, 오리지널 레이아웃 (업그레이드 46개): 플레이어별 최대 레벨과 시작 레벨, 전체 기본값, 각 플레이어가 기본값을 따르는지.",
  "Upgrade settings, Brood War layout (61 upgrades, one pad byte after the use-default column).": "업그레이드 설정, 브루드 워 레이아웃 (업그레이드 61개, 기본값 사용 열 뒤에 채움 바이트 하나).",
  "Upgrade settings, original layout (46 upgrades): use-default, then mineral, gas and time base costs and per-level factors.": "업그레이드 설정, 오리지널 레이아웃 (업그레이드 46개): 기본값 사용, 그다음 미네랄, 가스, 시간의 기본 비용과 레벨당 증가량.",
  "Went to {target}.": "{target}(으)로 이동했습니다.",
  "Which of the 64 CUWP slots are in use (StarEdit's bookkeeping).": "CUWP 슬롯 64개 중 쓰이는 것 (StarEdit의 내부 기록).",
  "Which of the fields below are set.": "아래 필드 중 설정된 것.",
  "Which special properties the game may read for this unit.": "게임이 이 유닛에서 읽을 수 있는 특수 속성.",
  "Who controls each of the twelve player slots: human, computer, rescuable, neutral, …": "열두 플레이어 슬롯을 각각 누가 조종하는지: 사람, 컴퓨터, 구출 가능, 중립, …",
  "Write every changed section into the map": "바뀐 섹션을 모두 맵에 씁니다",
  "after the selected one": "선택한 섹션 뒤",
  "at the end": "끝에",
  "at {offset}": "{offset} 위치",
  "before the selected one": "선택한 섹션 앞",
  "bits": "비트",
  "byte {offset}": "바이트 {offset}",
  "changed — not applied": "바뀜 — 적용 안 함",
  "char": "문자",
  "chars": "문자열",
  "choose": "선택",
  "contents": "내용",
  "custom name…": "직접 입력…",
  "cut": "잘림",
  "edited": "편집됨",
  "filter": "필터",
  "find hex or text": "16진수나 텍스트 찾기",
  "go to 0x…": "이동 0x…",
  "hex": "16진수",
  "insert": "삽입",
  "last wins": "마지막 것 사용",
  "length": "길이",
  "location {n}": "로케이션 {n}",
  "mode": "모드",
  "name": "이름",
  "not a whole number of {n}-byte records": "{n}바이트 레코드의 정수배가 아님",
  "number": "숫자",
  "occurrence {n} of {count}": "{count}개 중 {n}번째",
  "of {n}": "/ {n}",
  "offset": "오프셋",
  "overwrite": "덮어쓰기",
  "position": "위치",
  "raw": "원본",
  "rename": "새 이름",
  "runs past the end of the section": "섹션 끝을 넘어감",
  "section": "섹션",
  "selected": "선택",
  "size": "크기",
  "sprite {n}": "스프라이트 {n}",
  "text": "텍스트",
  "the game expects {n} bytes": "게임은 {n}바이트를 기대합니다",
  "typing in": "입력 위치",
  "unchanged": "바뀌지 않음",
  "unit {n}": "유닛 {n}",
  "units.dat id.": "units.dat ID.",
  "unknown": "알 수 없음",
  "unknown section": "알 수 없는 섹션",
  "unsaved": "저장 안 됨",
  "value": "값",
  "what the game reads now (repeats combined)": "게임이 지금 읽는 내용 (반복된 것 합침)",
  "zeros": "0으로 채움",
  "{bytes} bytes, {n, plural, one {# section} other {# sections}}": "{bytes}바이트, 섹션 {n}개",
  "{count} records of {size}": "{size}바이트 레코드 {count}개",
  "{mode} on repeat": "반복 시 {mode}",
  "{n, plural, one {# entry} other {# entries}}, {size} bytes": "항목 {n}개, {size}바이트",
  "{n, plural, one {# section has} other {# sections have}} changes you have not applied — Apply, Revert, or press Close again to drop them.": "섹션 {n}개에 적용하지 않은 변경이 있습니다. 적용하거나 되돌리세요. 버리려면 닫기를 한 번 더 누르세요.",
  "{n, plural, one {String index {list}} other {String indexes {list}}}, NUL-terminated.": "문자열 인덱스 {list}, NUL로 끝남.",
  "{name} at {offset} — {what}": "{offset}의 {name} — {what}",
  "{n} bytes": "{n}바이트",
  "{n} repeated": "{n}개 반복",
  "{n} unknown": "{n}개 알 수 없음",
};
